import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: `Create Next App`,
  description: `Generated by create next app`,
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);

export default RootLayout;
